# Generated by Django 5.2.2 on 2025-06-16 00:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Profile picture', max_length=255, null=True, verbose_name='image'),
        ),
    ]
