# Generated by Django 5.2.2 on 2025-06-10 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project name or title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Project description and details')),
                ('start_date', models.DateField(auto_now_add=True, help_text='When the project started')),
                ('target_end', models.DateField(blank=True, help_text='Target end date for the project (optional)', null=True)),
                ('cover_photo', models.ImageField(blank=True, help_text='Cover photo for the project', null=True, upload_to='project_covers/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects_project',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['owner', '-created'], name='projects_pr_owner_i_f69fcc_idx'), models.Index(fields=['-created'], name='projects_pr_created_5ace3f_idx')],
            },
        ),
    ]
