# Generated by Django 5.2.2 on 2025-06-11 22:58

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_photo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Cover photo for the project', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('caption', models.TextField(blank=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('mime_type', models.CharField(blank=True, max_length=50)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('exif_data', models.JSONField(blank=True, help_text='Camera EXIF data', null=True)),
                ('needs_attention', models.BooleanField(default=False, help_text='Mark for review')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature in project gallery')),
                ('order_index', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='projects.project')),
            ],
            options={
                'ordering': ['order_index', 'uploaded_at'],
                'indexes': [models.Index(fields=['project', 'order_index'], name='projects_ph_project_cb78a9_idx'), models.Index(fields=['uploaded_at'], name='projects_ph_uploade_51ce24_idx'), models.Index(fields=['needs_attention'], name='projects_ph_needs_a_b8fafd_idx'), models.Index(fields=['is_featured'], name='projects_ph_is_feat_5c8cee_idx')],
            },
        ),
    ]
