# Generated by Django 5.2.3 on 2025-06-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_cover_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='needs_attention',
            field=models.BooleanField(default=False),
        ),
    ]
